Functional props va yl
learn-academy-2023-charlie/react-challenges pull request #26
Opened 2023-05-04 23:10 UTC by lanyuke

2023-05-09 23:56 UTC, nmaresrivera11 requested changes
Hey, yarn.lock is floating outside of the repo. Can you remove that please?

2023-05-10 00:04 UTC, m3vance commented
deleted yarn.lock

2023-05-11 00:18 UTC, SunkissedQueen approved these changes

2023-05-11 14:40 UTC, nmaresrivera11 approved these changes

2023-05-11 15:11 UTC, merged